// Initialise the global array that allows the lookup of the depth of a given object
// GM2.0 does not have a depth on objects so on import from 1.x a global array is created
// NOTE: MacroExpansion is used to insert the array initialisation at import time
gml_pragma( "global", "__global_object_depths()");

// insert the generated arrays here
global.__objectDepths[0] = -10; // player_obj
global.__objectDepths[1] = 0; // playerDeath_obj
global.__objectDepths[2] = 0; // scythe_obj
global.__objectDepths[3] = -13; // camera_obj
global.__objectDepths[4] = 0; // dashEffect_obj
global.__objectDepths[5] = 0; // globalSettings_obj
global.__objectDepths[6] = 0; // hitbox_obj
global.__objectDepths[7] = 0; // hitboxEnemy_obj
global.__objectDepths[8] = 0; // hitboxEnemyBig_obj
global.__objectDepths[9] = 0; // finish_obj
global.__objectDepths[10] = 0; // snowfall_obj
global.__objectDepths[11] = 0; // fog_obj
global.__objectDepths[12] = -10; // cursor_obj
global.__objectDepths[13] = -10; // titlemenu_obj
global.__objectDepths[14] = -10; // mainMenu_obj
global.__objectDepths[15] = -10; // settingmenu_obj
global.__objectDepths[16] = -10; // videosettingsMenu_obj
global.__objectDepths[17] = -10; // controlsMenu_obj
global.__objectDepths[18] = 1; // lavaBlock_obj
global.__objectDepths[19] = 1; // lavaBlock2_obj
global.__objectDepths[20] = 1; // lavaBlockRC_obj
global.__objectDepths[21] = 1; // lavaBlockLC_obj
global.__objectDepths[22] = 1; // castleBlock_obj
global.__objectDepths[23] = 0; // woodBlock_obj
global.__objectDepths[24] = 11; // woodBlock2_obj
global.__objectDepths[25] = 0; // leafBlock_obj
global.__objectDepths[26] = 2; // treeBlock_obj
global.__objectDepths[27] = 5; // treeBlock2_obj
global.__objectDepths[28] = 2; // specialBlock_obj
global.__objectDepths[29] = 2; // mysteryBlockSpecial_obj
global.__objectDepths[30] = 0; // checkpointMystery_obj
global.__objectDepths[31] = 0; // grassBlockMystery_obj
global.__objectDepths[32] = 2; // quicksandBlock_obj
global.__objectDepths[33] = 3; // glassBlock_obj
global.__objectDepths[34] = 0; // glassBlockBroken_obj
global.__objectDepths[35] = 0; // explosiveBlock_obj
global.__objectDepths[36] = 1; // ladder_obj
global.__objectDepths[37] = 1; // ladderIron_obj
global.__objectDepths[38] = 0; // checkpoint_obj
global.__objectDepths[39] = 0; // easyModeBlock_obj
global.__objectDepths[40] = 1; // destroyCooldown_obj
global.__objectDepths[41] = 0; // stoneBlock_obj
global.__objectDepths[42] = 0; // woodBlockNew_obj
global.__objectDepths[43] = 10; // woodBlockNewBG_obj
global.__objectDepths[44] = 1; // snowBlock_obj
global.__objectDepths[45] = 2; // snowBlock2_obj
global.__objectDepths[46] = 1; // sniwBlockRC_obj
global.__objectDepths[47] = 1; // snowBlockLC_obj
global.__objectDepths[48] = 2; // grassBlock_obj
global.__objectDepths[49] = 2; // grassBlockRC_obj
global.__objectDepths[50] = 2; // grassBlockLC_obj
global.__objectDepths[51] = 2; // grassBlock2_obj
global.__objectDepths[52] = 0; // darkBlock_obj
global.__objectDepths[53] = 0; // darkBlockFake_obj
global.__objectDepths[54] = -11; // water_obj
global.__objectDepths[55] = -8; // waterEffect_obj
global.__objectDepths[56] = 0; // colliderGV_UF1_obj
global.__objectDepths[57] = 0; // colliderUF1_UF2_obj
global.__objectDepths[58] = 0; // colliderUF2_UF3_obj
global.__objectDepths[59] = 0; // colliderUF3_UFB_obj
global.__objectDepths[60] = 0; // colliderGV_UC1_obj
global.__objectDepths[61] = 0; // colliderUC1_UC2_obj
global.__objectDepths[62] = 0; // colliderUC2_UC3_obj
global.__objectDepths[63] = 0; // colliderUC3_UC2_SC_obj
global.__objectDepths[64] = 0; // colliderUC2_UC1_SC_obj
global.__objectDepths[65] = 0; // colliderUC3_DK1_obj
global.__objectDepths[66] = 0; // colliderDK1_DK2_obj
global.__objectDepths[67] = 0; // colliderDK2_DK3_obj
global.__objectDepths[68] = 0; // colliderUFB_DK3_obj
global.__objectDepths[69] = 0; // colliderDK3_DK2_obj
global.__objectDepths[70] = 0; // colliderDK2_DK1_obj
global.__objectDepths[71] = 0; // colliderUC3_SG1_obj
global.__objectDepths[72] = 0; // colliderSG1_SG2_obj
global.__objectDepths[73] = 0; // colliderDK1_SG2_obj
global.__objectDepths[74] = 0; // colliderSG2_SG3_obj
global.__objectDepths[75] = 0; // colliderSG3_DP_obj
global.__objectDepths[76] = 0; // colliderDP_UF1_obj
global.__objectDepths[77] = 0; // colliderGV_OP
global.__objectDepths[78] = 0; // spawn_obj
global.__objectDepths[79] = 0; // spawn1_obj
global.__objectDepths[80] = 0; // spawn2_obj
global.__objectDepths[81] = 0; // spawn3_obj
global.__objectDepths[82] = 0; // spawn4_obj
global.__objectDepths[83] = -3; // blueFlower_obj
global.__objectDepths[84] = -3; // redFlower_obj
global.__objectDepths[85] = 5; // latern_obj
global.__objectDepths[86] = -4; // lamp_obj
global.__objectDepths[87] = 1; // tutorialSign1_obj
global.__objectDepths[88] = 1; // tutorialSign2_obj
global.__objectDepths[89] = 1; // tutorialSign3_obj
global.__objectDepths[90] = 1; // tutorialSign4_obj
global.__objectDepths[91] = 1; // tutorialSign5_obj
global.__objectDepths[92] = 0; // bird_obj
global.__objectDepths[93] = 0; // birdSpawner_obj
global.__objectDepths[94] = 0; // dude_obj
global.__objectDepths[95] = 3; // house_obj
global.__objectDepths[96] = 2; // doorTutorial_obj
global.__objectDepths[97] = 2; // OPDoor_obj
global.__objectDepths[98] = 5; // rope_obj
global.__objectDepths[99] = 0; // enemyNormal_obj
global.__objectDepths[100] = 0; // enemyBatSpawner_obj
global.__objectDepths[101] = 0; // enemyBat_obj
global.__objectDepths[102] = 0; // enemySpirit_obj
global.__objectDepths[103] = 0; // enemyNormal2_obj
global.__objectDepths[104] = 0; // enemyMystery_obj
global.__objectDepths[105] = 0; // enemy_obj
global.__objectDepths[106] = 0; // enemyFlyingCloud_obj
global.__objectDepths[107] = 0; // flyingCloud_obj
global.__objectDepths[108] = 0; // lever_obj
global.__objectDepths[109] = 0; // leverBlue_obj
global.__objectDepths[110] = 0; // leverRed_obj
global.__objectDepths[111] = 0; // trapdoor_obj
global.__objectDepths[112] = 0; // trapdoorBlue_obj
global.__objectDepths[113] = 0; // trapdoorRed_obj
global.__objectDepths[114] = 0; // batBossSprite_obj
global.__objectDepths[115] = 0; // batBoss_obj
global.__objectDepths[116] = 0; // lockedBlockBat_obj
global.__objectDepths[117] = 0; // npcLola_obj
global.__objectDepths[118] = 3; // monitor_obj
global.__objectDepths[119] = 0; // spikeUp_obj
global.__objectDepths[120] = 0; // spikeHalf_obj
global.__objectDepths[121] = 0; // lava_obj
global.__objectDepths[122] = 0; // spikeMystery_obj
global.__objectDepths[123] = -1; // turret_obj
global.__objectDepths[124] = -1; // bullet_obj
global.__objectDepths[125] = 0; // spikeBig_obj
global.__objectDepths[126] = -3; // spikeBigFalling_obj
global.__objectDepths[127] = 0; // demon_obj
global.__objectDepths[128] = 0; // demonSpawner_obj
global.__objectDepths[129] = -1; // orbRed_obj
global.__objectDepths[130] = 0; // saw_obj
global.__objectDepths[131] = 10; // pipe_obj
global.__objectDepths[132] = 0; // lightFlickering_obj
global.__objectDepths[133] = 0; // light_obj
global.__objectDepths[134] = -4; // lightControlNormal_obj
global.__objectDepths[135] = -4; // lightControlHeavy_obj
global.__objectDepths[136] = -4; // lightControlFull_obj
global.__objectDepths[137] = -2; // key_obj
global.__objectDepths[138] = -2; // redOrb_obj
global.__objectDepths[139] = -2; // blueOrb_obj
global.__objectDepths[140] = 0; // darkSpirit_obj
global.__objectDepths[141] = 0; // darkSpiritBig_obj
global.__objectDepths[142] = 0; // petBirdPA_obj
global.__objectDepths[143] = 0; // petBird_obj
global.__objectDepths[144] = 0; // warpzone_obj
global.__objectDepths[145] = 0; // scytheReload_obj
global.__objectDepths[146] = -100; // vignetteShaderBlue_obj
global.__objectDepths[147] = -100; // vignetteShaderRed_obj
global.__objectDepths[148] = 0; // lensflareStillBlue_obj
global.__objectDepths[149] = 0; // lensflareStillYellow_obj
global.__objectDepths[150] = 0; // lensflareFollowYellow_obj
global.__objectDepths[151] = 0; // lensflareFollowBlue_obj
global.__objectDepths[152] = 0; // dirtyLensEffect_obj
global.__objectDepths[153] = 0; // shopIcon1_obj
global.__objectDepths[154] = 0; // shopIcon2_obj
global.__objectDepths[155] = 0; // particleYellow_obj
global.__objectDepths[156] = 0; // particleYellowSpawner_obj


global.__objectNames[0] = "player_obj";
global.__objectNames[1] = "playerDeath_obj";
global.__objectNames[2] = "scythe_obj";
global.__objectNames[3] = "camera_obj";
global.__objectNames[4] = "dashEffect_obj";
global.__objectNames[5] = "globalSettings_obj";
global.__objectNames[6] = "hitbox_obj";
global.__objectNames[7] = "hitboxEnemy_obj";
global.__objectNames[8] = "hitboxEnemyBig_obj";
global.__objectNames[9] = "finish_obj";
global.__objectNames[10] = "snowfall_obj";
global.__objectNames[11] = "fog_obj";
global.__objectNames[12] = "cursor_obj";
global.__objectNames[13] = "titlemenu_obj";
global.__objectNames[14] = "mainMenu_obj";
global.__objectNames[15] = "settingmenu_obj";
global.__objectNames[16] = "videosettingsMenu_obj";
global.__objectNames[17] = "controlsMenu_obj";
global.__objectNames[18] = "lavaBlock_obj";
global.__objectNames[19] = "lavaBlock2_obj";
global.__objectNames[20] = "lavaBlockRC_obj";
global.__objectNames[21] = "lavaBlockLC_obj";
global.__objectNames[22] = "castleBlock_obj";
global.__objectNames[23] = "woodBlock_obj";
global.__objectNames[24] = "woodBlock2_obj";
global.__objectNames[25] = "leafBlock_obj";
global.__objectNames[26] = "treeBlock_obj";
global.__objectNames[27] = "treeBlock2_obj";
global.__objectNames[28] = "specialBlock_obj";
global.__objectNames[29] = "mysteryBlockSpecial_obj";
global.__objectNames[30] = "checkpointMystery_obj";
global.__objectNames[31] = "grassBlockMystery_obj";
global.__objectNames[32] = "quicksandBlock_obj";
global.__objectNames[33] = "glassBlock_obj";
global.__objectNames[34] = "glassBlockBroken_obj";
global.__objectNames[35] = "explosiveBlock_obj";
global.__objectNames[36] = "ladder_obj";
global.__objectNames[37] = "ladderIron_obj";
global.__objectNames[38] = "checkpoint_obj";
global.__objectNames[39] = "easyModeBlock_obj";
global.__objectNames[40] = "destroyCooldown_obj";
global.__objectNames[41] = "stoneBlock_obj";
global.__objectNames[42] = "woodBlockNew_obj";
global.__objectNames[43] = "woodBlockNewBG_obj";
global.__objectNames[44] = "snowBlock_obj";
global.__objectNames[45] = "snowBlock2_obj";
global.__objectNames[46] = "sniwBlockRC_obj";
global.__objectNames[47] = "snowBlockLC_obj";
global.__objectNames[48] = "grassBlock_obj";
global.__objectNames[49] = "grassBlockRC_obj";
global.__objectNames[50] = "grassBlockLC_obj";
global.__objectNames[51] = "grassBlock2_obj";
global.__objectNames[52] = "darkBlock_obj";
global.__objectNames[53] = "darkBlockFake_obj";
global.__objectNames[54] = "water_obj";
global.__objectNames[55] = "waterEffect_obj";
global.__objectNames[56] = "colliderGV_UF1_obj";
global.__objectNames[57] = "colliderUF1_UF2_obj";
global.__objectNames[58] = "colliderUF2_UF3_obj";
global.__objectNames[59] = "colliderUF3_UFB_obj";
global.__objectNames[60] = "colliderGV_UC1_obj";
global.__objectNames[61] = "colliderUC1_UC2_obj";
global.__objectNames[62] = "colliderUC2_UC3_obj";
global.__objectNames[63] = "colliderUC3_UC2_SC_obj";
global.__objectNames[64] = "colliderUC2_UC1_SC_obj";
global.__objectNames[65] = "colliderUC3_DK1_obj";
global.__objectNames[66] = "colliderDK1_DK2_obj";
global.__objectNames[67] = "colliderDK2_DK3_obj";
global.__objectNames[68] = "colliderUFB_DK3_obj";
global.__objectNames[69] = "colliderDK3_DK2_obj";
global.__objectNames[70] = "colliderDK2_DK1_obj";
global.__objectNames[71] = "colliderUC3_SG1_obj";
global.__objectNames[72] = "colliderSG1_SG2_obj";
global.__objectNames[73] = "colliderDK1_SG2_obj";
global.__objectNames[74] = "colliderSG2_SG3_obj";
global.__objectNames[75] = "colliderSG3_DP_obj";
global.__objectNames[76] = "colliderDP_UF1_obj";
global.__objectNames[77] = "colliderGV_OP";
global.__objectNames[78] = "spawn_obj";
global.__objectNames[79] = "spawn1_obj";
global.__objectNames[80] = "spawn2_obj";
global.__objectNames[81] = "spawn3_obj";
global.__objectNames[82] = "spawn4_obj";
global.__objectNames[83] = "blueFlower_obj";
global.__objectNames[84] = "redFlower_obj";
global.__objectNames[85] = "latern_obj";
global.__objectNames[86] = "lamp_obj";
global.__objectNames[87] = "tutorialSign1_obj";
global.__objectNames[88] = "tutorialSign2_obj";
global.__objectNames[89] = "tutorialSign3_obj";
global.__objectNames[90] = "tutorialSign4_obj";
global.__objectNames[91] = "tutorialSign5_obj";
global.__objectNames[92] = "bird_obj";
global.__objectNames[93] = "birdSpawner_obj";
global.__objectNames[94] = "dude_obj";
global.__objectNames[95] = "house_obj";
global.__objectNames[96] = "doorTutorial_obj";
global.__objectNames[97] = "OPDoor_obj";
global.__objectNames[98] = "rope_obj";
global.__objectNames[99] = "enemyNormal_obj";
global.__objectNames[100] = "enemyBatSpawner_obj";
global.__objectNames[101] = "enemyBat_obj";
global.__objectNames[102] = "enemySpirit_obj";
global.__objectNames[103] = "enemyNormal2_obj";
global.__objectNames[104] = "enemyMystery_obj";
global.__objectNames[105] = "enemy_obj";
global.__objectNames[106] = "enemyFlyingCloud_obj";
global.__objectNames[107] = "flyingCloud_obj";
global.__objectNames[108] = "lever_obj";
global.__objectNames[109] = "leverBlue_obj";
global.__objectNames[110] = "leverRed_obj";
global.__objectNames[111] = "trapdoor_obj";
global.__objectNames[112] = "trapdoorBlue_obj";
global.__objectNames[113] = "trapdoorRed_obj";
global.__objectNames[114] = "batBossSprite_obj";
global.__objectNames[115] = "batBoss_obj";
global.__objectNames[116] = "lockedBlockBat_obj";
global.__objectNames[117] = "npcLola_obj";
global.__objectNames[118] = "monitor_obj";
global.__objectNames[119] = "spikeUp_obj";
global.__objectNames[120] = "spikeHalf_obj";
global.__objectNames[121] = "lava_obj";
global.__objectNames[122] = "spikeMystery_obj";
global.__objectNames[123] = "turret_obj";
global.__objectNames[124] = "bullet_obj";
global.__objectNames[125] = "spikeBig_obj";
global.__objectNames[126] = "spikeBigFalling_obj";
global.__objectNames[127] = "demon_obj";
global.__objectNames[128] = "demonSpawner_obj";
global.__objectNames[129] = "orbRed_obj";
global.__objectNames[130] = "saw_obj";
global.__objectNames[131] = "pipe_obj";
global.__objectNames[132] = "lightFlickering_obj";
global.__objectNames[133] = "light_obj";
global.__objectNames[134] = "lightControlNormal_obj";
global.__objectNames[135] = "lightControlHeavy_obj";
global.__objectNames[136] = "lightControlFull_obj";
global.__objectNames[137] = "key_obj";
global.__objectNames[138] = "redOrb_obj";
global.__objectNames[139] = "blueOrb_obj";
global.__objectNames[140] = "darkSpirit_obj";
global.__objectNames[141] = "darkSpiritBig_obj";
global.__objectNames[142] = "petBirdPA_obj";
global.__objectNames[143] = "petBird_obj";
global.__objectNames[144] = "warpzone_obj";
global.__objectNames[145] = "scytheReload_obj";
global.__objectNames[146] = "vignetteShaderBlue_obj";
global.__objectNames[147] = "vignetteShaderRed_obj";
global.__objectNames[148] = "lensflareStillBlue_obj";
global.__objectNames[149] = "lensflareStillYellow_obj";
global.__objectNames[150] = "lensflareFollowYellow_obj";
global.__objectNames[151] = "lensflareFollowBlue_obj";
global.__objectNames[152] = "dirtyLensEffect_obj";
global.__objectNames[153] = "shopIcon1_obj";
global.__objectNames[154] = "shopIcon2_obj";
global.__objectNames[155] = "particleYellow_obj";
global.__objectNames[156] = "particleYellowSpawner_obj";


// create another array that has the correct entries
var len = array_length_1d(global.__objectDepths);
global.__objectID2Depth = [];
for( var i=0; i<len; ++i ) {
	var objID = asset_get_index( global.__objectNames[i] );
	if (objID >= 0) {
		global.__objectID2Depth[ objID ] = global.__objectDepths[i];
	} // end if
} // end for